### PR TITLE
timeout fix / observer refactor

### LINKED ISSUE #1526: bug: observer: error timing out jobs
I see a lot of error messages like the following in the observer logs:

```
2021/08/05 18:37:39 error timing out job "test-unit" for event "7d9f73ad-2e83-40ef-960b-18bbf62e3d86": Event "7d9f73ad-2e83-40ef-960b-18bbf62e3d86" job "test-unit" has already reached a terminal phase.
```

The overwhelming volume of messages like this one tells me we're probably, mistakenly, failing to stop the timer on jobs that have already been observed as complete.

### PR DESCRIPTION
**Pull request by krancour**
Fixes #1526 

Also follows up on #1506, which after further review, was more complex than it needed to be.

### CODE REVIEW

File: v2/observer/jobs.go [hunk 1]
```diff
@@ -38,81 +38,102 @@ func (o *observer) syncJobPods(ctx context.Context) {
...
-		if containerStatus.Name == pod.Spec.Containers[0].Name {
-			if containerStatus.State.Terminated != nil {
-				status.Ended = &containerStatus.State.Terminated.FinishedAt.Time
+	if pod.DeletionTimestamp != nil {
+		// This pod has been deleted. Pods usually hang around for a while after
+		// they complete before they are deleted (to ensure the log agent has enough
+		// time to capture all logs), so the job's final transition to a terminal
+		// phase has PROBABLY been recorded already, BUT given the possibility that
+		// the job's pod was manually deleted by an operator, we'll attempt a final
+		// phase change to ABORTED here, knowing that it will simple fail if the job
```
Comment (vdice) [inline v2/observer/jobs.go:104]:
```suggestion
		// phase change to ABORTED here, knowing that it will simply fail if the job
```

File: v2/observer/workers.go [hunk 2]
```diff
@@ -38,195 +38,101 @@ func (o *observer) syncWorkerPods(ctx context.Context) {
...
-						eventID,
-					),
-				)
+	if pod.DeletionTimestamp != nil {
+		// This pod has been deleted. Pods usually hang around for a while after
+		// they complete before they are deleted (to ensure the log agent has enough
+		// time to capture all logs), so the worker's final transition to a terminal
+		// phase has PROBABLY been recorded already, BUT given the possibility that
+		// the worker's pod was manually deleted by an operator, we'll attempt a
+		// final phase change to ABORTED here, knowing that it will simple fail if
```
Comment (vdice) [inline v2/observer/workers.go:101]:
```suggestion
		// final phase change to ABORTED here, knowing that it will simply fail if
```

**Review by vdice — APPROVED** [review]
LGTM

File: v2/observer/jobs.go (hunk 1 above)
Comment (krancour) [reply v2/observer/jobs.go]: Fixed

File: v2/observer/workers.go (hunk 2 above)
Comment (krancour) [reply v2/observer/workers.go]: Fixed
