### PR TITLE
Check message before logging it

### LINKED ISSUE #969: Check if body.message is defined before logging it in worker
```
/home/src/dist/k8s.js:518
                this.logger.error(error.body.message);
                                             ^

  TypeError: Cannot read property 'message' of undefined                                                                                                                            
  - k8s.js:518 Request.request [as _callback]                                                                                                                                           /home/src/dist/k8s.js:518:46                                                                                                                                                    
  - request.js:185 self.callback                                                                                                                                                        [src]/[request]/request.js:185:22                                                                                                                                               
  - request.js:881 Request.onRequestError                                                                                                                                               [src]/[request]/request.js:881:8                                                                                                                                                

error Command failed with exit code 1.
```

### PR DESCRIPTION
**Pull request by aidarbek**
**What this PR does / why we need it**:
Checks if a message is present before logging it. Closes #969 
**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

### CODE REVIEW

File: brigade-worker/src/k8s.ts [hunk 1]
```diff
@@ -769,7 +769,9 @@ export class JobRunner implements jobs.JobRunner {
         });
         const req = request(requestOptions, (error, response, body) => {
           if (error) {
-            this.logger.error(error.body.message);
+            if (error.body.message) {
```
Comment (mumoshu) [inline brigade-worker/src/k8s.ts]:
```suggestion
            if (error.body) {
```

@aidarbek Thanks for the PR!

I think you'd rather check for `error.body` here as the error indicates that `error.body` can be undefined:

```
/home/src/dist/k8s.js:518
                this.logger.error(error.body.message);
                                             ^

  TypeError: Cannot read property 'message' of undefined            
```
