### PR TITLE
fix: delete all associated events on project delete

### LINKED ISSUE #1517: bug: when a project is deleted, its events are logically delete, but never physically deleted as intended

### PR DESCRIPTION
**Pull request by krancour**
Fixes #1517

### CODE REVIEW

File: v2/apiserver/internal/api/events.go [hunk 1]
```diff
@@ -949,7 +949,10 @@ type EventsStore interface {
 	// return a *meta.ErrNotFound error.
 	Delete(context.Context, string) error
 	// DeleteMany unconditionally deletes multiple Events specified by the
-	// EventsSelector parameter from the underlying data store.  Implementations
+	// EventsSelector parameter from the underlying data store. Implementations
 	// MUST return the total number of deleted events.
 	DeleteMany(context.Context, EventsSelector) (<-chan Event, int64, error)
+	// DeleteByProjectID unconditionally deleted all Events associated with the
```
Comment (vdice) [inline v2/apiserver/internal/api/events.go:955]:
```suggestion
	// DeleteByProjectID unconditionally deletes all Events associated with the
```

**Review by vdice — APPROVED** [review]

File: v2/apiserver/internal/api/events.go (hunk 1 above)
Comment (krancour) [reply v2/apiserver/internal/api/events.go]: Fixed
