### PR TITLE
fix(kind/new-cluster): prevent error when kind cluster already exists

### LINKED ISSUE #1549: docs & hack: make hack-new-kind-cluster
We should _name_ the kind cluster so that it won't conflict with an existing cluster having the default name "cluster."

### PR DESCRIPTION
**Pull request by adamreese**
Fixes #1549

### CODE REVIEW

**Review by vdice — APPROVED** [review]
LGTM!  Just needs a [signed commit](https://github.com/brigadecore/community/blob/master/contributing.md#signed-commits) when convenient.

**Review by vdice — COMMENTED** [review]
One thing to double-check: Can you run `DOCKER_REGISTRY=localhost:5000 make hack` to deploy to the newly-created kind cluster?  For some reason, although the images push to the localhost:5000 registry for me, the core component pods on the kind node hit ErrImagePull.  Not sure why that would be yet... (same flow appears to work on the v2 branch.)

File: hack/kind/new-cluster.sh [hunk 1]
```diff
@@ -30,14 +30,16 @@ EOF
 
 # Make sure the local Docker image registry is connected to the same network
 # as the kind cluster
-docker network connect "kind" "${reg_name}" || true
+if ! docker network inspect kind >/dev/null 2>&1; then
```
Comment (vdice) [inline hack/kind/new-cluster.sh:33]: I think this may be the added piece that may be tripping me up... for instance if the `kind` docker network persists but I have created a new kind cluster and registry... with this logic, the necessary `docker network connect` command would be skipped.

Comment (krancour) [reply hack/kind/new-cluster.sh:33]: Ya... if it's a new registry and existing network, this leads to a problem.

Comment (krancour) [reply hack/kind/new-cluster.sh]: I fixed this, signed the commit, and force pushed.

**Review by vdice — APPROVED** [review]
